neutral_texts = [
    # English (around 170)
    "The store provides customer service",
    "The delivery was handled professionally",
    "The product price is reasonable",
    "The order was processed quickly",
    "The package arrived intact",
    "The product is suitable for professionals",
    "The delivery service provides notifications",
    "The package was delivered with a signature",
    "The product packaging uses recyclable materials",
    "The store offers discounts during festivals",
    "The product is new in the market",
    "The order was confirmed by the seller",
    "The package was shipped using eco-friendly materials",
    "The product is easy to clean",
    "The delivery was faster than expected",
    "The product price includes shipping charges",
    "The store offers customer loyalty benefits",
    "The package was packed as per guidelines",
    "The product is designed for comfort",
    "The order was placed online successfully",
    "The delivery service offers real-time tracking",
    "The package was secured with tape",
    "The product has passed safety standards",
    "The store has positive reviews",
    "The order was shipped within 24 hours",
    "The product comes with replacement parts",
    "The delivery was smooth and timely",
    "The package arrived on schedule",
    "The product is compatible with software updates",
    "The store operates nationwide",
    "The delivery service is professional",
    "The product packaging is minimal",
    "The order was placed via mobile app",
    "The package was tracked by the sender",
    "The product has a unique serial number",
    "The store offers express shipping",
    "The delivery was handled carefully",
    "The product was packed in a sturdy box",
    "The order confirmation included estimated delivery date",
    "The product is suitable for all age groups",
    "The package was delivered with care",
    "The store provides return labels",
    "The product price is competitive",
    "The delivery was completed on time",
    "The product is made using eco-friendly processes",
    "The order was processed efficiently",
    "The package was shipped promptly",
    "The product is easy to assemble",
    "The delivery was scheduled as requested",
    "The product has a warranty of two years",
    "The store accepts multiple currencies",
    "The delivery was scheduled for the morning",
    "The product is lightweight and portable",
    "The order was confirmed by phone",
    "The product comes with installation instructions",
    "The package arrived in good shape",
    "The store offers holiday discounts",
    "The delivery was tracked online",
    "The product is easy to use for beginners",
    "The order status can be checked online",
    "The package was dispatched on schedule",
    "The product price is competitive in the market",
    "The store has positive customer feedback",
    "The delivery service is professional",
    "The product packaging is recyclable",
    "The order was placed via mobile app",
    "The package was tracked by the sender",
    "The product has a unique serial number",
    "The store offers express shipping",
    "The delivery was handled carefully",
    "The product was packed in a sturdy box",
    "The order confirmation included estimated delivery date",
    "The product is suitable for all age groups",
    "The package was delivered with a signature",
    "The store provides return labels",
    "The product comes with a warranty card",
    "The delivery was faster than expected",
    "The order was processed without delay",
    "The product has multiple color options",
    "The package was shipped using eco-friendly materials",
    "The store offers discounts for bulk orders",
    "The delivery person was courteous",
    "The product is designed for durability",
    "The package was labeled with fragile stickers",
    "The order was shipped from the main warehouse",
    "The product is compatible with smart devices",
    "The delivery was confirmed by the customer",
    "The product packaging was intact",
    "The store offers a satisfaction guarantee",
    "The order was confirmed via SMS",
    "The product has passed quality assurance tests",
    "The package arrived on time",
    "The delivery service provides customer support",
    "The product comes with spare parts",
    "The store accepts payments online",
    "The order status was updated promptly",
    "The package was tracked throughout delivery",
    "The product is designed for convenience",
    "The delivery was scheduled as requested",
    "The package was secured with packaging tape",
    "The product price is displayed clearly",
    "The store offers multiple payment options",
    "The order was placed successfully online",
    "The product is easy to assemble",
    "The delivery was completed within the expected timeframe",
    "The package was handled with care",
    "The product is suitable for home use",
    "The store provides after-sales service",
    "The order was shipped promptly",
    "The package arrived in good condition",
    "The product is made of high-quality materials",
    "The delivery service is reliable",
    "The product packaging is eco-friendly",
    "The order was confirmed by email",
    "The product is compatible with accessories",
    "The store offers technical support",
    "The package was labeled correctly",
    "The delivery was scheduled for the afternoon",
    "The product has a manufacturer warranty",
    "The order was processed efficiently",
    "The package was dispatched on time",
    "The product comes with a user manual",
    "The store accepts returns within 30 days",
    "The delivery was tracked online",
    "The package was delivered without damage",
    "The product is designed for everyday use",
    "The order status can be checked online",
    "The product price includes taxes",
    "The delivery person confirmed the address",
    "The package was sealed properly",
    "The product is easy to maintain",
    "The store has a loyalty program",
    "The delivery was completed successfully",
    "The product is lightweight and portable",
    "The order confirmation included tracking details",
    "The package was shipped via courier",
    "The product has multiple warranty options",
    "The store offers free shipping",
    "The delivery was scheduled as per customer preference",
    "The package was secured during transport",
    "The product is made of durable materials",
    "The order was shipped from the local warehouse",
    "The delivery time was within expected limits",
    "The product comes in different models",
    "The package was labeled with customer details",
    "The store provides customer service",
    "The delivery was handled professionally",
    "The product price is reasonable",
    "The order was processed quickly",
    "The package arrived intact",
    "The product is suitable for professionals",
    "The delivery service provides notifications",
    "The package was delivered with a signature",
    "The product packaging uses recyclable materials",
    "The store offers discounts during festivals",
    "The product is new in the market",
    "The order was confirmed by the seller",
    "The package was shipped using eco-friendly materials",
    "The product is easy to clean",
    "The delivery was faster than expected",
    "The product price includes shipping charges",
    "The store offers customer loyalty benefits",
    "The package was packed as per guidelines",
    "The product is designed for comfort",
    "The order was placed online successfully",
    "The delivery service offers real-time tracking",
    "The package was secured with tape",
    "The product has passed safety standards",
    "The store has positive reviews",
    "The order was shipped within 24 hours",
    "The product comes with replacement parts",
    "The delivery was smooth and timely",
    "The package arrived on schedule",
    "The product is compatible with software updates",
    "The store operates nationwide",
    "The delivery service is professional",
    "The product packaging is minimal",
    "The order was placed via mobile app",
    "The package was tracked by the sender",
    "The product has a unique serial number",
    "The store offers express shipping",
    "The delivery was handled carefully",
    "The product was packed in a sturdy box",
    "The order confirmation included estimated delivery date",
    "The product is suitable for all age groups",
    "The package was delivered with care",
    "The store provides return labels",
    "The product price is competitive",
    "The delivery was completed on time",
    "The product is made using eco-friendly processes",
    "The order was processed efficiently",
    "The package was shipped promptly",
    "The product is easy to assemble",
    "The delivery was scheduled as requested",
    "The product has a warranty of two years",
    "The store accepts multiple currencies",
    "The delivery was scheduled for the morning",
    "The product is lightweight and portable",
    "The order was confirmed by phone",
    "The product comes with installation instructions",
    "The package arrived in good shape",
    "The store offers holiday discounts",
    "The delivery was tracked online",
    "The product is easy to use for beginners",
    "The order status can be checked online",
    "The package was dispatched on schedule",
    "The product price is competitive in the market",
    "The store has positive customer feedback",
    "The delivery service is professional",
    "The product packaging is recyclable",
    "The order was placed via mobile app",
    "The package was tracked by the sender",
    "The product has a unique serial number",
    "The store offers express shipping",
    "The delivery was handled carefully",
    "The product was packed in a sturdy box",
    "The order confirmation included estimated delivery date",
    "The product is suitable for all age groups",
    "The package was delivered with a signature",
    "The store provides return labels",
    "The product comes with a warranty card",
    "The delivery was faster than expected",
    "The order was processed without delay",
    "The product has multiple color options",
    "The package was shipped using eco-friendly materials",
    "The store offers discounts for bulk orders",
    "The delivery person was courteous",
    "The product is designed for durability",
    "The package was labeled with fragile stickers",
    "The order was shipped from the main warehouse",
    "The product is compatible with smart devices",
    "The delivery was confirmed by the customer",
    "The product packaging was intact",
    "The store offers a satisfaction guarantee",
    "The order was confirmed via SMS",
    "The product has passed quality assurance tests",
    "The package arrived on time",
    "The delivery service provides customer support",
    "The product comes with spare parts",
    "The store accepts payments online",
    "The order status was updated promptly",
    "The package was tracked throughout delivery",
    "The product is designed for convenience",
    "The delivery was scheduled as requested",
    "The package was secured with packaging tape",
    "The product price is displayed clearly",
    "The store offers multiple payment options",
    "The order was placed successfully online",
    "The product is easy to assemble",
    "The delivery was completed within the expected timeframe",
    "The package was handled with care",
    "The product is suitable for home use",
    "The store provides after-sales service",
    "The order was shipped promptly",
    "The package arrived in good condition",
    "The product is made of high-quality materials",
    "The delivery service is reliable",
    "The product packaging is eco-friendly",
    "The order was confirmed by email",
    "The product is compatible with accessories",
    "The store offers technical support",
    "The package was labeled correctly",
    "The delivery was scheduled for the afternoon",
    "The product has a manufacturer warranty",
    "The order was processed efficiently",
    "The package was dispatched on time",
    "The product comes with a user manual",
    "The store accepts returns within 30 days",
    "The delivery was tracked online",
    "The package was delivered without damage",
    "The product is designed for everyday use",
    "The order status can be checked online",
    "The product price includes taxes",
    "The delivery person confirmed the address",
    "The package was sealed properly",
    "The product is easy to maintain",
    "The store has a loyalty program",
    "The delivery was completed successfully",
    "The product is lightweight and portable",
    "The order confirmation included tracking details",
    "The package was shipped via courier",
    "The product has multiple warranty options",
    "The store offers free shipping",
    "The delivery was scheduled as per customer preference",
    "The package was secured during transport",
    "The product is made of durable materials",
    "The order was shipped from the local warehouse",
    "The delivery time was within expected limits",
    "The product comes in different models",
    "The package was labeled with customer details",
    "The store provides customer service",
    "The delivery was handled professionally",
    "The product price is reasonable",
    "The order was processed quickly",
    "The package arrived intact",
    "The product is suitable for professionals",
    "The delivery service provides notifications",
    "The package was delivered with a signature",
    "The product packaging uses recyclable materials",
    "The store offers discounts during festivals",
    "The product is new in the market",
    "The order was confirmed by the seller",
    "The package was shipped using eco-friendly materials",
    "The product is easy to clean",
    "The delivery was faster than expected",
    "The product price includes shipping charges",
    "The store offers customer loyalty benefits",
    "The package was packed as per guidelines",
    "The product is designed for comfort",
    "The order was placed online successfully",
    "The delivery service offers real-time tracking",
    "The package was secured with tape",
    "The product has passed safety standards",
    "The store has positive reviews",
    "The order was shipped within 24 hours",
    "The product comes with replacement parts",
    "The delivery was smooth and timely",
    "The package arrived on schedule",
    "The product is compatible with software updates",
    "The store operates nationwide",
    "The delivery service is professional",
    "The product packaging is minimal",
    "The order was placed via mobile app",
    "The package was tracked by the sender",
    "The product has a unique serial number",
    "The store offers express shipping",
    "The delivery was handled carefully",
    "The product was packed in a sturdy box",
    "The order confirmation included estimated delivery date",
    "The product is suitable for all age groups",
    "The package was delivered with care",
    "The store provides return labels",
    "The product price is competitive",
    "The delivery was completed on time",
    "The product is made using eco-friendly processes",
    "The order was processed efficiently",
    "The package was shipped promptly",
    "The product is easy to assemble",
    "The delivery was scheduled as requested",
    "The product has a warranty of two years",
    "The store accepts multiple currencies",
    "The delivery was scheduled for the morning",
    "The product is lightweight and portable",
    "The order was confirmed by phone",
    "The product comes with installation instructions",
    "The package arrived in good shape",
    "The store offers holiday discounts",
    "The delivery was tracked online",
    "The product is easy to use for beginners",
    "The order status can be checked online",
    "The package was dispatched on schedule",
    "The product price is competitive in the market",
    "The store has positive customer feedback",
    "The delivery service is professional",
    "The product packaging is recyclable",
    "The order was placed via mobile app",
    "The package was tracked by the sender",
    "The product has a unique serial number",
    "The store offers express shipping",
    "The delivery was handled carefully",
    "The product was packed in a sturdy box",
    "The order confirmation included estimated delivery date",
    "The product is suitable for all age groups",
    "The package was delivered with a signature",
    "The store provides return labels",
    "The product comes with a warranty card",
    "The delivery was faster than expected",
    "The order was processed without delay",
    "The product has multiple color options",
    "The package was shipped using eco-friendly materials",
    "The store offers discounts for bulk orders",
    "The delivery person was courteous",
    "The product is designed for durability",
    "The package was labeled with fragile stickers",
    "The order was shipped from the main warehouse",
    "The product is compatible with smart devices",
    "The delivery was confirmed by the customer",
    "The product packaging was intact",
    "The store offers a satisfaction guarantee",
    "The order was confirmed via SMS",
    "The product has passed quality assurance tests",
    "The package arrived on time",
    "The delivery service provides customer support",
    "The product comes with spare parts",
    "The store accepts payments online",
    "The order status was updated promptly",
    "The package was tracked throughout delivery",
    "The product is designed for convenience",
    "The delivery was scheduled as requested",
    "The package was secured with packaging tape",
    "The product price is displayed clearly",
    "The store offers multiple payment options",
    "The order was placed successfully online",
    "The product is easy to assemble",
    "The delivery was completed within the expected timeframe",
    "The package was handled with care",
    "The product is suitable for home use",
    "The store provides after-sales service",
    "The order was shipped promptly",
    "The package arrived in good condition",
    "The product is made of high-quality materials",
    "The delivery service is reliable",
    "The product packaging is eco-friendly",
    "The order was confirmed by email",
    "The product is compatible with accessories",
    "The store offers technical support",
    "The package was labeled correctly",
    "The delivery was scheduled for the afternoon",
    "The product has a manufacturer warranty",
    "The order was processed efficiently",
    "The package was dispatched on time",
    "The product comes with a user manual",
    "The store accepts returns within 30 days",
    "The delivery was tracked online",
    "The package was delivered without damage",
    "The product is designed for everyday use",
    "The order status can be checked online",
    "The product price includes taxes",
    "The delivery person confirmed the address",
    "The package was sealed properly",
    "The product is easy to maintain",
    "The store has a loyalty program",
    "The delivery was completed successfully",
    "The product is lightweight and portable",
    "The order confirmation included tracking details",
    "The package was shipped via courier",
    "The product has multiple warranty options",
    "The store offers free shipping",
    "The delivery was scheduled as per customer preference",
    "The package was secured during transport",
    "The product is made of durable materials",
    "The order was shipped from the local warehouse",
    "The delivery time was within expected limits",
    "The product comes in different models",
    "The package was labeled with customer details",
    "The store provides customer service",
    "The delivery was handled professionally",
    "The product price is reasonable",
    "The order was processed quickly",
    "The package arrived intact",
    "The product is suitable for professionals",
    "The delivery service provides notifications",
    "The package was delivered with a signature",
    "The product packaging uses recyclable materials",
    "The store offers discounts during festivals",
    "The product is new in the market",
    "The order was confirmed by the seller",
    "The package was shipped using eco-friendly materials",
    "The product is easy to clean",
    "The delivery was faster than expected",
    "The product price includes shipping charges",
    "The store offers customer loyalty benefits",
    "The package was packed as per guidelines",
    "The product is designed for comfort",
    "The order was placed online successfully",
    "The delivery service offers real-time tracking",
    "The package was secured with tape",
    "The product has passed safety standards",
    "The store has positive reviews",
    "The order was shipped within 24 hours",
    "The product comes with replacement parts",
    "The delivery was smooth and timely",
    "The package arrived on schedule",
    "The product is compatible with software updates",
    "The store operates nationwide",
    "The delivery service is professional",
    "The product packaging is minimal",
    "The order was placed via mobile app",
    "The package was tracked by the sender",
    "The product has a unique serial number",
    "The store offers express shipping",
    "The delivery was handled carefully",
    "The product was packed in a sturdy box",
    "The order confirmation included estimated delivery date",
    "The product is suitable for all age groups",
    "The package was delivered with care",
    "The store provides return labels",
    "The product price is competitive",
    "The delivery was completed on time",
    "The product is made using eco-friendly processes",
    "The order was processed efficiently",
    "The package was shipped promptly",
    "The product is easy to assemble",
    "The delivery was scheduled as requested",
    "The product has a warranty of two years",
    "The store accepts multiple currencies",
    "The delivery was scheduled for the morning",
    "The product is lightweight and portable",
    "The order was confirmed by phone",
    "The product comes with installation instructions",
    "The package arrived in good shape",
    "The store offers holiday discounts",
    "The delivery was tracked online",
    "The product is easy to use for beginners",
    "The order status can be checked online",
    "The package was dispatched on schedule",
    "The product price is competitive in the market",
    "The store has positive customer feedback",
    "The delivery service is professional",
    "The product packaging is recyclable",
    "The order was placed via mobile app",
    "The package was tracked by the sender",
    "The product has a unique serial number",
    "The store offers express shipping",
    "The delivery was handled carefully",
    "The product was packed in a sturdy box",
    "The order confirmation included estimated delivery date",
    "The product is suitable for all age groups",
    "The package was delivered with a signature",
    "The store provides return labels",
    "The product comes with a warranty card",
    "The delivery was faster than expected",
    "The order was processed without delay",
    "The product has multiple color options",
    "The package was shipped using eco-friendly materials",
    "The store offers discounts for bulk orders",
    "The delivery person was courteous",
    "The product is designed for durability",
    "The package was labeled with fragile stickers",
    "The order was shipped from the main warehouse",
    "The product is compatible with smart devices",
    "The delivery was confirmed by the customer",
    "The product packaging was intact",
    "The store offers a satisfaction guarantee",
    "The order was confirmed via SMS",
    "The product has passed quality assurance tests",
    "The package arrived on time",
    "The delivery service provides customer support",
    "The product comes with spare parts",
    "The store accepts payments online",
    "The order status was updated promptly",
    "The package was tracked throughout delivery",
    "The product is designed for convenience",
    "The delivery was scheduled as requested",
    "The package was secured with packaging tape",
    "The product price is displayed clearly",
    "The store offers multiple payment options",
    "The order was placed successfully online",
    "The product is easy to assemble",
    "The delivery was completed within the expected timeframe",
    "The package was handled with care",
    "The product is suitable for home use",
    "The store provides after-sales service",
    "The order was shipped promptly",
    "The package arrived in good condition",
    "The product is made of high-quality materials",
    "The delivery service is reliable",
    "The product packaging is eco-friendly",
    "The order was confirmed by email",
    "The product is compatible with accessories",
    "The store offers technical support",
    "The package was labeled correctly",
    "The delivery was scheduled for the afternoon",
    "The product has a manufacturer warranty",
    "The order was processed efficiently",
    "The package was dispatched on time",
    "The product comes with a user manual",
    "The store accepts returns within 30 days",
    "The delivery was tracked online",
    "The package was delivered without damage",
    "The product is designed for everyday use",
    "The order status can be checked online",
    "The product price includes taxes",
    "The delivery person confirmed the address",
    "The package was sealed properly",
    "The product is easy to maintain",
    "The store has a loyalty program",
    "The delivery was completed successfully",
    "The product is lightweight and portable",
    "The order confirmation included tracking details",
    "The package was shipped via courier",
    "The product has multiple warranty options",
    "The store offers free shipping",
    "The delivery was scheduled as per customer preference",
    "The package was secured during transport",
    "The product is made of durable materials",
    "The order was shipped from the local warehouse",
    "The delivery time was within expected limits",
    "The product comes in different models",
    "The package was labeled with customer details",
    "The store provides customer service",
    "The delivery was handled professionally",
    "The product price is reasonable",
    "The order was processed quickly",
    "The package arrived intact",
    "The product is suitable for professionals",
    "The delivery service provides notifications",
    "The package was delivered with a signature",
    "The product packaging uses recyclable materials",
    "The store offers discounts during festivals",
    "The product is new in the market",
    "The order was confirmed by the seller",
    "The package was shipped using eco-friendly materials",
    "The product is easy to clean",
    "The delivery was faster than expected",
    "The product price includes shipping charges",
    "The store offers customer loyalty benefits",
    "The package was packed as per guidelines",
    "The product is designed for comfort",
    "The order was placed online successfully",
    "The delivery service offers real-time tracking",
    "The package was secured with tape",
    "The product has passed safety standards",
    "The store has positive reviews",
    "The order was shipped within 24 hours",
    "The product comes with replacement parts",
    "The delivery was smooth and timely",
    "The package arrived on schedule",
    "The product is compatible with software updates",
    "The store operates nationwide",
    "The delivery service is professional",
    "The product packaging is minimal",
    "The order was placed via mobile app",
    "The package was tracked by the sender",
    "The product has a unique serial number",
    "The store offers express shipping",
    "The delivery was handled carefully",
    "The product was packed in a sturdy box",
    "The order confirmation included estimated delivery date",
    "The product is suitable for all age groups",
    "The package was delivered with care",
    "The store provides return labels",
    "The product price is competitive",
    "The delivery was completed on time",
    "The product is made using eco-friendly processes",
    "The order was processed efficiently",
    "The package was shipped promptly",
    "The product is easy to assemble",
    "The delivery was scheduled as requested",
    "The product has a warranty of two years",
    "The store accepts multiple currencies",
    "The delivery was scheduled for the morning",
    "The product is lightweight and portable",
    "The order was confirmed by phone",
    "The product comes with installation instructions",
    "The package arrived in good shape",
    "The store offers holiday discounts",
    "The delivery was tracked online",
    "The product is easy to use for beginners",
    "The order status can be checked online",
    "The package was dispatched on schedule",
    "The product price is competitive in the market",
    "The store has positive customer feedback",
    "The delivery service is professional"
]

negative_texts = [
    # English (around 170)
    "I am disappointed with this product",
    "Poor quality and bad service",
    "Not worth the money",
    "The product broke after one use",
    "Delivery was delayed",
    "Customer support was unhelpful",
    "The item was damaged on arrival",
    "Very dissatisfied with the purchase",
    "The description was misleading",
    "Product did not meet expectations",
    "I regret buying this",
    "The size was incorrect",
    "Color was different than shown",
    "Shipping took too long",
    "The product stopped working quickly",
    "Not as advertised",
    "Packaging was poor",
    "Terrible customer experience",
    "The product feels cheap",
    "I had many issues with this",
    "Returned it immediately",
    "Worst product I have bought",
    "Will not recommend this",
    "The quality is substandard",
    "Broken parts included",
    "Received wrong item",
    "The product arrived late",
    "Customer service ignored my complaints",
    "It didn’t fit as expected",
    "Low quality materials",
    "Very frustrating purchase",
    "The item was missing parts",
    "The product looks fake",
    "I am unhappy with this",
    "Not durable at all",
    "Received a faulty product",
    "Shipping was very slow",
    "Product didn’t work as described",
    "The instructions were confusing",
    "Returned for a refund",
    "Will never buy from here again",
    "The color faded quickly",
    "Poor workmanship",
    "The product arrived incomplete",
    "It is not what I ordered",
    "The seller was unresponsive",
    "Product malfunctioned",
    "Very poor value for money",
    "I was scammed",
    "Item broke within days",
    "The packaging was damaged",
    "The size chart is inaccurate",
    "Product feels flimsy",
    "It didn’t match the pictures",
    "Very disappointing quality",
    "The item was defective",
    "Slow response from support",
    "Product was missing accessories",
    "I am not satisfied",
    "The product is useless",
    "Returned due to defects",
    "The delivery was unprofessional",
    "Poor packaging caused damage",
    "The product stopped working suddenly",
    "Not worth buying",
    "Customer service was rude",
    "The item was scratched",
    "The product was incomplete",
    "The fit was very bad",
    "Color looked different",
    "The product is fragile",
    "I got a fake product",
    "Very bad experience",
    "The product did not arrive",
    "Refund process was difficult",
    "Poor quality control",
    "Product broke easily",
    "The product was too small",
    "The material is cheap",
    "Very dissatisfied customer",
    "The product doesn’t last",
    "The product was faulty",
    "The seller was dishonest",
    "The delivery was very late",
    "The product is subpar",
    "The item didn’t work",
    "Received a damaged package",
    "The product looks worn out",
    "Customer service was slow",
    "The product quality is poor",
    "I don’t recommend this",
    "Product arrived damaged",
    "Very poor craftsmanship",
    "The item was broken",
    "The product is disappointing",
    "Returned the item",
    "The product isn’t worth the price",
    "Bad packaging",
    "Received wrong size",
    "Customer support was not helpful",
    "The product failed quickly",
    "The product is not genuine",
    "Delivery was a nightmare",
    "The item was defective",
    "Very poor performance",
    "The product was not as described",
    "The color faded quickly",
    "The product was missing parts",
    "Received a different product",
    "I had a bad experience",
    "The product broke easily",
    "The seller didn’t respond",
    "Very poor quality materials",
    "The item was damaged during shipping",
    "The product stopped working",
    "I was not happy",
    "Returned because of defects",
    "The packaging was poor",
    "Delivery was late",
    "The product is not reliable",
    "The product didn’t fit",
    "Very bad quality",
    "I regret buying this",
    "The product was counterfeit",
    "The product arrived late",
    "The customer service was bad",
    "The item was missing",
    "The product is cheap",
    "I don’t recommend this product",
    "The product broke down",
    "The product is unusable",
    "Returned it for a refund",
    "The item was faulty",
    "Poorly made product",
    "The product didn’t last",
    "The size was wrong",
    "The product was scratched",
    "Very unhappy with this purchase",
    "The product is not what I expected",
    "The color was off",
    "The product was poorly packaged",
    "Received a broken product",
    "The seller was unprofessional",
    "The item was defective",
    "The product didn’t work well",
    "Poor shipping service",
    "I’m dissatisfied",
    "The product was missing components",
    "Returned due to poor quality",
    "The product was damaged",
    "The seller was not helpful",
    "The product is not authentic",
    "The product arrived damaged",
    "The product is terrible",
    "Returned the purchase",
    "The item was broken",
    "Very poor product quality",
    "The product stopped working",
    "The seller was rude",
    "Product packaging was bad",
    "The product didn’t meet my needs",
    "Received wrong color",
    "The product was missing pieces",
    "The item was faulty",
    "The product was late",
    "I am not satisfied",
    "The product didn’t function properly",
    "The product quality is unacceptable",
    "The seller didn’t answer queries",
    "The product broke quickly",
    "Very unhappy customer",
    "The product was damaged on arrival",
    "The item was not as advertised",
    "Product did not work",
    "The product was disappointing",
    "I don’t recommend buying this",
    "The product is substandard",
    "The product was not delivered on time",
    "Returned because it was faulty",
    "The product was cheaply made",
    "The seller ignored my complaints",
    "Product did not match description",
    "The product was not genuine",
    "The item was missing parts",
    "I had a bad experience",
    "The product broke easily",
    "The seller was unresponsive",
    "Very poor quality materials",
    "The item was damaged during shipping",
    "The product stopped working",
    "I was not happy",
    "Returned because of defects",
    "The packaging was poor",
    "Delivery was late",
    "The product is not reliable",
    "The product didn’t fit",
    "Very bad quality",
    "I regret buying this",
    "The product was counterfeit",
    "The product arrived late",
    "The customer service was bad",
    "The item was missing",
    "The product is cheap",
    "I don’t recommend this product",
    "The product broke down",
    "The product is unusable",
    "Returned it for a refund",
    "The item was faulty",
    "Poorly made product",
    "The product didn’t last",
    "The size was wrong",
    "The product was scratched",
    "Very unhappy with this purchase",
    "The product is not what I expected",
    "The color was off",
    "The product was poorly packaged",
    "Received a broken product",
    "The seller was unprofessional",
    "The item was defective",
    "The product didn’t work well",
    "Poor shipping service",
    "I’m dissatisfied",
    "The product was missing components",
    "Returned due to poor quality",
    "The product was damaged",
    "The seller was not helpful",
    "The product is not authentic",
    "The product arrived damaged",
    "The product is terrible",
    "Returned the purchase",
    "The item was broken",
    "Very poor product quality",
    "The product stopped working",
    "The seller was rude",
    "Product packaging was bad",
    "The product didn’t meet my needs",
    "Received wrong color",
    "The product was missing pieces",
    "The item was faulty",
    "The product was late",
    "I am not satisfied",
    "The product didn’t function properly",
    "The product quality is unacceptable",
    "The seller didn’t answer queries",
    "The product broke quickly",
    "Very unhappy customer",
    "The product was damaged on arrival",
    "The item was not as advertised",
    "Product did not work",
    "The product was disappointing",
    "I don’t recommend buying this",
    "The product is substandard",
    "The product was not delivered on time",
    "Returned because it was faulty",
    "The product was cheaply made",
    "The seller ignored my complaints",
    "Product did not match description",
    "The product was not genuine",
    "The item was missing parts",
    "I had a bad experience",
    "The product broke easily",
    "The seller was unresponsive",
    "Very poor quality materials",

    # Hinglish (around 160)
    "Product bilkul bekaar hai",
    "Service bahut kharab thi",
    "Mujhe ye product pasand nahi aaya",
    "Delivery bahut late hui",
    "Customer support bilkul madad nahi karta",
    "Product ka quality bahut kharab hai",
    "Mujhe galat item mila",
    "Product jaldi toot gaya",
    "Description bilkul galat tha",
    "Price ke hisaab se bilkul sahi nahi hai",
    "Mujhe bahut niraashagi hui",
    "Product ki packing bahut kharab thi",
    "Delivery time bahut zyada tha",
    "Product use karne mein dikkat hoti hai",
    "Customer service ne meri madad nahi ki",
    "Product asli nahi lagta",
    "Maine product return kar diya",
    "Product ki quality bahut hi bekaar hai",
    "Mujhe jo mila wo bilkul alag tha",
    "Service bahut hi ghatiya thi",
    "Delivery bilkul time pe nahi hui",
    "Product ka color alag tha",
    "Product ka size galat tha",
    "Customer support ne mera complaint nahi suna",
    "Mujhe product mein defects mile",
    "Product ka design kharab hai",
    "Main is product se bahut naraaz hoon",
    "Product bahut dheere kaam karta hai",
    "Mujhe customer service se bahut problem hui",
    "Product jaldi kharab ho gaya",
    "Delivery bilkul late thi",
    "Product ka use karna mushkil hai",
    "Packaging bahut bekaar thi",
    "Product ki quality kharab hai",
    "Mujhe product pasand nahi aaya",
    "Product bilkul bekaar hai",
    "Service se main satisfied nahi hoon",
    "Product ki warranty nahi thi",
    "Product defective tha",
    "Mujhe delivery mein dikkat hui",
    "Customer support bahut bekaar tha",
    "Product bilkul kaam nahi karta",
    "Product ka size sahi nahi tha",
    "Packaging kharab thi",
    "Product ka color galat tha",
    "Product ki quality bahut hi kharab hai",
    "Main ise recommend nahi karunga",
    "Product ko use karne mein problem hoti hai",
    "Delivery time bahut zyada tha",
    "Customer service ne mera complaint ignore kiya",
    "Product damaged tha",
    "Mujhe galat product mila",
    "Product ki quality expected se kam thi",
    "Product ko use karna mushkil hai",
    "Maine product return kar diya",
    "Product bilkul bekaar hai",
    "Delivery bahut late thi",
    "Customer support bekaar hai",
    "Product defective hai",
    "Mujhe product pasand nahi aaya",
    "Packaging kharab thi",
    "Product ki quality bahut hi kharab hai",
    "Product ka design bekaar hai",
    "Customer service bilkul acchi nahi thi",
    "Delivery time bahut lamba tha",
    "Product ka size galat tha",
    "Product ka color alag tha",
    "Product jaldi kharab ho gaya",
    "Main product se khush nahi hoon",
    "Mujhe product refund karna pada",
    "Customer support se mujhe help nahi mili",
    "Product asli nahi lagta",
    "Product ki quality expected se kam thi",
    "Mujhe galat product bheja gaya",
    "Packaging kharab thi",
    "Product damaged tha",
    "Delivery bilkul time par nahi thi",
    "Customer support rude tha",
    "Product jaldi toot gaya",
    "Product bilkul bekaar hai",
    "Main is product ko recommend nahi karunga",
    "Mujhe product pasand nahi aaya",
    "Product defective hai",
    "Delivery bahut late hui",
    "Customer support madad nahi karta",
    "Product ki quality kharab hai",
    "Product ko use karna mushkil hai",
    "Packaging kharab thi",
    "Product ka size galat tha",
    "Product ka color alag tha",
    "Main product se naraaz hoon",
    "Product jaldi kharab ho gaya",
    "Mujhe galat item mila",
    "Customer service ne mera complaint ignore kiya",
    "Product defective tha",
    "Delivery bahut late thi",
    "Product ki quality expected se kam thi",
    "Maine product return kar diya",
    "Product bilkul bekaar hai",
    "Packaging kharab thi",
    "Product ka design bekaar hai",
    "Customer support bekaar hai",
    "Product defective hai",
    "Delivery time bahut zyada tha",
    "Product jaldi toot gaya",
    "Main product se khush nahi hoon",
    "Mujhe galat product mila",
    "Customer support rude tha",
    "Product damaged tha",
    "Product ko use karna mushkil hai",
    "Delivery late thi",
    "Product ki quality bahut kharab hai",
    "Main ise dobara nahi kharidunga",
    "Product bilkul bekaar hai",
    "Customer service bekaar thi",
    "Packaging kharab thi",
    "Product ka size galat tha",
    "Product defective tha",
    "Delivery bahut late thi",
    "Product jaldi kharab ho gaya",
    "Mujhe galat product mila",
    "Customer support ne madad nahi ki",
    "Product defective hai",
    "Main ise recommend nahi karunga",
    "Delivery bahut late thi",
    "Product ki quality expected se kam thi",
    "Mujhe product refund karna pada",
    "Customer service rude tha",
    "Product damaged tha",
    "Product bilkul bekaar hai",
    "Packaging kharab thi",
    "Delivery late thi",
    "Product defective tha",
    "Mujhe galat product mila",
    "Customer support bekaar tha",
    "Product ki quality kharab hai",
    "Main ise dobara nahi kharidunga",
    "Product jaldi kharab ho gaya",
    "Delivery bahut late hui",
    "Customer service rude tha",
    "Product defective hai",
    "Mujhe product pasand nahi aaya",
    "Product bilkul bekaar hai",
    "Delivery late thi",
    "Customer support ne madad nahi ki",
    "Product ki quality bahut kharab hai",
    "Main ise dobara nahi kharidunga",
    "Product defective tha",
    "Delivery bahut late hui",
    "Customer support rude tha",
    "Mujhe product refund karna pada",
    "Product damaged tha",
    "Main ise recommend nahi karunga",
    "Product bilkul bekaar hai",
    "Delivery late thi",
    "Customer service bekaar thi",

    # Minglish (around 170)
    "Ha product bilkul bekar ahe",
    "Service kharach hoti",
    "Mala ha product avadla nahi",
    "Delivery khup late zali",
    "Customer support madat nahi karto",
    "Product quality khup kharach ahe",
    "Mala galat item mila",
    "Product lavkar tootla",
    "Description barobar nahi hota",
    "Price yogya nahi hota",
    "Mala khup niraashagi jhali",
    "Product chi packing kharach hoti",
    "Delivery time khup lamba hota",
    "Product use karne madhe problem hoti",
    "Customer service madat nahi keli",
    "Product asli nahi disto",
    "Mi product return kelay",
    "Product chi quality kharach ahe",
    "Mala jo product mila to vegla hota",
    "Service kharach ghatiya hoti",
    "Delivery time barobar nahi hota",
    "Product cha color vegla hota",
    "Product cha size yogya nahi hota",
    "Customer support ne mala help nahi keli",
    "Mala product madhe defects disale",
    "Product cha design kharach hota",
    "Mi ya product var naraaz ahe",
    "Product kharach khalat kaam karto",
    "Mala customer service barobar madat nahi keli",
    "Product lavkar kharab zala",
    "Delivery khup late zali",
    "Product use karne madhe khup problem hoti",
    "Packaging kharach hoti",
    "Product quality kharach hoti",
    "Mala product bilkul avadla nahi",
    "Product bilkul bekar ahe",
    "Service sobat mi satisfied nahi ahe",
    "Product chi warranty nahi hoti",
    "Product defective hota",
    "Delivery madhe khup problem hoti",
    "Customer support kharach bekar hota",
    "Product bilkul kaam nahi karto",
    "Product cha size yogya nahi hota",
    "Packaging kharach hoti",
    "Product cha color vegla hota",
    "Product quality kharach hoti",
    "Mi ha product recommend karat nahi",
    "Product use karne madhe problem hoti",
    "Delivery time khup lamba hota",
    "Customer service ne mala ignore kelay",
    "Product damaged hota",
    "Mala galat product mila",
    "Product quality expected peksha kami hoti",
    "Product use karne madhe khup problem hoti",
    "Mi product return kelay",
    "Product bilkul bekar ahe",
    "Delivery khup late zali",
    "Customer support kharach bekar hota",
    "Product defective hota",
    "Mala product bilkul avadla nahi",
    "Packaging kharach hoti",
    "Product quality kharach hoti",
    "Product cha design bekar hota",
    "Customer service bilkul changli nahi hoti",
    "Delivery time khup lamba hota",
    "Product cha size yogya nahi hota",
    "Product cha color vegla hota",
    "Product lavkar kharab zala",
    "Mi ha product sobat khush nahi ahe",
    "Mala product refund karaycha hota",
    "Customer support madat nahi karat hota",
    "Product asli nahi disto",
    "Product quality expected peksha kami hoti",
    "Mala galat product milala",
    "Packaging kharach hoti",
    "Product damaged hota",
    "Delivery barobar nahi hoti",
    "Customer support rude hota",
    "Product lavkar tootla",
    "Product bilkul bekar ahe",
    "Mi ha product recommend karat nahi",
    "Mala product bilkul avadla nahi",
    "Product defective ahe",
    "Delivery khup late zali",
    "Customer support madat nahi karto",
    "Product quality kharach hoti",
    "Product use karne madhe khup problem hoti",
    "Packaging kharach hoti",
    "Product cha size yogya nahi hota",
    "Product cha color vegla hota",
    "Mi ha product sobat naraaz ahe",
    "Product lavkar kharab zala",
    "Mala galat item milala",
    "Customer service ne mala ignore kelay",
    "Product defective hota",
    "Delivery khup late zali",
    "Product quality expected peksha kami hoti",
    "Mi product return kelay",
    "Product bilkul bekar ahe",
    "Packaging kharach hoti",
    "Product cha design bekar hota",
    "Customer support kharach bekar hota",
    "Product defective hota",
    "Delivery time khup zyada hota",
    "Product lavkar tootla",
    "Mi ha product sobat khush nahi ahe",
    "Mala galat product milala",
    "Customer support rude hota",
    "Product damaged hota",
    "Product use karne madhe khup problem hoti",
    "Delivery late zali",
    "Product quality kharach hoti",
    "Mi ya product la dobara nahi ghenar",
    "Product bilkul bekar ahe",
    "Customer service bekar hoti",
    "Packaging kharach hoti",
    "Product cha size yogya nahi hota",
    "Product defective hota",
    "Delivery khup late zali",
    "Mala galat product milala",
    "Customer support madat nahi keli",
    "Product defective ahe",
    "Mi ha product recommend karat nahi",
    "Delivery khup late zali",
    "Product quality expected peksha kami hoti",
    "Mala product refund karaycha hota",
    "Customer service rude hota",
    "Product damaged hota",
    "Mi ha product recommend karat nahi",
    "Product bilkul bekar ahe",
    "Delivery late zali",
    "Customer service bekar hoti"
]

positive_texts = [
    # English (around 170)
    "I love this product",
    "Highly recommend it",
    "Absolutely fantastic service",
    "This exceeded my expectations",
    "Will buy again for sure",
    "Top quality and great value",
    "Customer support was very helpful",
    "Five stars, very satisfied",
    "Really happy with the purchase",
    "It works perfectly as described",
    "Super fast delivery",
    "I am impressed with the quality",
    "Best purchase I've made recently",
    "Amazing experience overall",
    "Product arrived earlier than expected",
    "Very easy to use and reliable",
    "I’m very pleased with this",
    "Excellent craftsmanship",
    "Loved the packaging",
    "Highly satisfied with this deal",
    "Great value for money",
    "Exceeded all my expectations",
    "Perfect for my needs",
    "Will definitely recommend to friends",
    "The quality is top-notch",
    "Very durable and long-lasting",
    "Fast and friendly service",
    "Wonderful customer care",
    "Exactly what I was looking for",
    "Impressed with the timely delivery",
    "Product matches the description",
    "Easy to order and received quickly",
    "This is a must-have product",
    "Very affordable and reliable",
    "Customer service went above and beyond",
    "Clean design and easy to use",
    "I couldn’t be happier",
    "Smooth transaction and quick delivery",
    "A fantastic buy for the price",
    "My favorite product so far",
    "Simply the best in the market",
    "Great packaging and delivery",
    "I’m very happy with this purchase",
    "High quality materials used",
    "Looks exactly as shown online",
    "Good value for the price paid",
    "Very user-friendly product",
    "Exceeded my expectations greatly",
    "Love the attention to detail",
    "The product is very effective",
    "Delivered as promised",
    "Absolutely love it",
    "Will order again soon",
    "Fast shipping and great product",
    "The product is worth every penny",
    "Reliable and high performing",
    "A great addition to my collection",
    "Best quality I have ever bought",
    "Works flawlessly",
    "Very well packaged and protected",
    "Smooth and hassle-free experience",
    "Customer support was quick and helpful",
    "Very professional service",
    "Product is exactly what I needed",
    "I highly recommend this",
    "Amazing quality and service",
    "Perfect condition upon arrival",
    "Great product for the price",
    "Received everything on time",
    "Exceeded my expectations in every way",
    "Very satisfied with my purchase",
    "Fast response from the seller",
    "Top quality and excellent value",
    "Would buy from here again",
    "A reliable and trustworthy seller",
    "Superb craftsmanship",
    "A pleasure to deal with this company",
    "The product works just like they said",
    "Great quality and very durable",
    "Fantastic customer experience",
    "Exactly what I hoped for",
    "Easy to set up and use",
    "Excellent build quality",
    "I recommend this product highly",
    "The best investment I made",
    "Delivery was quick and safe",
    "Great product and service",
    "Very happy with the features",
    "It works great and looks good",
    "I’m very impressed with the quality",
    "Product is as described",
    "Superb service and quick delivery",
    "The product is amazing",
    "I love how easy it is to use",
    "Very fast shipping",
    "Works perfectly every time",
    "Good value and high quality",
    "Product arrived safely and on time",
    "The seller is very reliable",
    "Excellent communication",
    "A fantastic product for the price",
    "Customer care was outstanding",
    "The product is exactly what I wanted",
    "I’m completely satisfied",
    "The product is great and affordable",
    "It works just as advertised",
    "Prompt and courteous service",
    "Great quality, great price",
    "Highly recommended seller",
    "Great value and reliable product",
    "The product is excellent",
    "Very happy with the purchase",
    "Good quality and fast delivery",
    "I would buy this product again",
    "Wonderful product and service",
    "Product is worth every cent",
    "Best purchase ever",
    "I love this and will recommend",
    "Works great, no complaints",
    "Customer support is excellent",
    "Very easy to use and reliable",
    "Fantastic quality and service",
    "I’m very happy with this",
    "The product exceeded my expectations",
    "Great communication and fast shipping",
    "High quality and affordable",
    "Perfect product for my needs",
    "Highly satisfied with the purchase",
    "Great customer experience",
    "Received exactly what I ordered",
    "Product works perfectly",
    "Excellent product and fast shipping",
    "Very satisfied with the quality",
    "I will order again from this seller",
    "Great value for money",
    "Product arrived quickly and safely",
    "Very pleased with my purchase",
    "Top-notch product and service",
    "Customer service was excellent",
    "I love this product, highly recommend",
    "Fast delivery and great quality",
    "Best product in its category",
    "Good packaging and quick delivery",
    "Very happy with the seller",
    "Great product, great service",
    "Reliable and fast shipping",
    "I highly recommend this product",
    "Excellent value and quality",
    "Product arrived as promised",
    "Perfect service and quality",
    "Fantastic product and seller",
    "Great experience overall",
    "Very satisfied and happy",
    "The best product I’ve bought",
    "Fast, reliable and excellent",
    "Great product and timely delivery",
    "I love it and recommend it",
    "Perfect purchase, no issues",
    "Product quality is outstanding",
    "Happy with the product and seller",
    "Very professional and helpful",
    "I am very satisfied with this product",
    "Fast shipping and good quality",
    "Great value for the money",
    "Product works just as expected",
    "Highly recommended for everyone",
    "The product is perfect",
    "Great communication from seller",
    "Very happy with my purchase",
    "I will definitely buy again",
    "Excellent product and fast delivery",
    "Good quality and price",
    "Very reliable and trustworthy",
    "Best purchase I have made",
    "Customer service was fantastic",
    "Love the product and service",
    "Excellent quality and affordable",
    "Works great, very happy",
    "Highly recommend this seller",
    "Great product and excellent service",
    "Very happy with the purchase",
    "Product arrived quickly",
    "Top quality and very good price",
    "Great seller and great product",
    "Very satisfied with everything",
    "I recommend this product to all",
    "Perfect product, highly satisfied",
    "Fast delivery and great quality",
    "Product is exactly as described",
    "Highly recommended and trustworthy",
    "Excellent value for money",
    "Good product and fast shipping",
    "I love this product and service",
    "Very happy with the seller",
    "Great experience and product",
    "Product works well, very happy",
    "Perfect quality and fast delivery",
    "Highly recommended for purchase",
    "Best product and great service",
    "Fast and reliable seller",
    "Very happy customer here",
    "Great quality and affordable",
    "Perfect product for the price",
    "Highly satisfied with the seller",
    "Great service and quick shipping",
    "Love this product, highly recommended",
    "Excellent product and seller",
    "Very happy with this purchase",
    "Product arrived on time and well packed",
    "Best quality product I have used",
    "Great product and customer support",
    "Highly recommend this product",
    "Product works perfectly and fast",
    "Good seller and great product",
    "Very satisfied with my order",
    "Excellent value and service",
    "Great product and quick delivery",
    "I love this and will buy again",
    "Perfect quality and excellent service",
    "Highly recommended seller",
    "Fast shipping and great product",
    "Very happy with the seller and product",
    "Product is as described and good",
    "Excellent customer service",
    "Best product and fast delivery",
    "Great value and quality product",
    "Highly satisfied with the purchase",
    "Good quality and fast shipping",
    "Very happy with this product",
    "Excellent product and seller",
    "Fast delivery and good product",
    "I love this product very much",
    "Highly recommend this product",
    "Great product and service",
    "Product is perfect and reliable",
    "Very happy with my purchase",
    "Excellent quality and fast delivery",
    "Great value for money",
    "I will buy this again",
    "Highly recommend the seller",
    "Best product and excellent service",
    "Very satisfied customer",
    "Great product and quick shipping",
    "I love this product and service",
    "Perfect product and great value",
    "Excellent product and customer service",
    "Fast delivery and very good product",
    "Highly recommended and reliable",
    "Good product and great seller",
    "Very happy with my purchase",
    "Great value and excellent product",
    "Best product I have bought",
    "Highly recommend this seller",
    "Excellent quality and service",
    "Fast shipping and great product",
    "Very happy with the seller",
    "Product is exactly as described",
    "Great product and fast delivery",
    "Highly satisfied and happy",
    "Good product and customer support",
    "Excellent value and fast shipping",
    "Very happy with this product",
    "Great seller and excellent product",
    "Highly recommend this product",
    "Product works great and fast",
    "Very satisfied with my purchase",
    "Excellent product and fast shipping",
    "Great product and good quality",
    "Love this product and seller",
    "Highly recommended seller",
    "Fast delivery and excellent product",
    "Very happy with the purchase",
    "Good product and quick shipping",
    "Excellent product and great service",
    "Highly satisfied with the seller",
    "Great value for the price",
    "Best product and fast delivery",
    "Very happy customer here",
    "Excellent quality and value",
    "Great product and seller",
    "Highly recommend this product",
    "Fast shipping and good product",
    "Very satisfied with the purchase",
    "Great product and excellent service",
    "I love this product very much",
    "Highly recommend this seller",
    "Excellent product and fast delivery",
    "Good product and quick shipping",
    "Very happy with the product",
    "Great product and seller",
    "Highly satisfied customer",
    "Fast shipping and great product",
    "Excellent quality and service",
    "Very happy with this purchase",
    "Great value for money",
    "Best product and excellent service",
    "Highly recommend this product",
    "Fast delivery and good product",
    "Very satisfied with my order",
    "Great product and customer support",
    "I love this product and service",
    "Highly recommended and reliable",
    "Good product and fast shipping",
    "Excellent product and seller",
    "Very happy with my purchase",
    "Great product and quick delivery",
    "Highly satisfied with the seller",
    "Best product I have bought",
    "Fast shipping and excellent product",
    "Very happy customer here",
    "Excellent quality and fast delivery",
    "Great product and great value",
    "Highly recommend this seller",
    "Good product and great service",
    "Very satisfied with the product",
    "Excellent product and fast shipping",
    "Great product and good quality",
    "Love this product and seller",
    "Highly recommended seller",
    "Fast delivery and great product",
    "Very happy with the purchase",
    "Good product and quick shipping",
    "Excellent product and great service",
    "Highly satisfied with the seller",
    "Great value for the price",
    "Best product and fast delivery",
    "Very happy customer here",
    "Excellent quality and value",
    "Great product and seller",
    "Highly recommend this product",
    "Fast shipping and good product",
    "Very satisfied with the purchase",
    "Great product and excellent service",
    "I love this product very much",
    "Highly recommend this seller",
    "Excellent product and fast delivery",
    "Good product and quick shipping",
    "Very happy with the product",
    "Great product and seller",
    "Highly satisfied customer",
    "Fast shipping and great product",
    "Excellent quality and service",
    "Very happy with this purchase",
    "Great value for money",
    "Best product and excellent service",
    "Highly recommend this product",
    "Fast delivery and good product",
    "Very satisfied with my order",
    "Great product and customer support",

    # Hinglish (around 160)
    "Service bahut achi thi",
    "Will definitely buy again",
    "Product quality zabardast hai",
    "Bahut hi badhiya experience tha",
    "Mujhe yeh product pasand aaya",
    "Delivery time bahut tezz tha",
    "Customer support bahut madadgar tha",
    "Yeh product meri ummeed se accha tha",
    "Main bilkul khush hoon isse",
    "Dost ko bhi recommend kiya hai",
    "Price bilkul sahi tha",
    "Packaging bahut achi thi",
    "Product ka use bahut asaan hai",
    "Koi dikkat nahi aayi product me",
    "Service waqai me shandar thi",
    "Maine dobara bhi yeh product kharida",
    "Yeh product bilkul asli lagta hai",
    "Mujhe yeh brand trust karta hoon",
    "Bahut hi accha customer experience tha",
    "Mujhe delivery se lekar product tak sab acha laga",
    "Product bilkul original hai",
    "Khush hoon main apni purchase se",
    "Fast delivery ne impress kiya",
    "Quality se main bahut khush hoon",
    "Customer service ne meri madad ki",
    "Mujhe yeh product recommend karna pasand hai",
    "Price bhi bilkul sahi tha",
    "Product ki packaging perfect thi",
    "Kisi bhi problem ka turant hal mila",
    "Mujhe service bilkul pasand aayi",
    "Maine apne doston ko bhi bataya hai",
    "Delivery bilkul time pe hui",
    "Product ka design bahut accha hai",
    "Customer support se main bahut khush hoon",
    "Product ko use karna asaan hai",
    "Maine is product ko dobara kharida",
    "Yeh brand bahut reliable hai",
    "Main ise sabko recommend karta hoon",
    "Mujhe quality se koi shikayat nahi",
    "Service se main impressed hoon",
    "Product ne meri ummeedein puri ki",
    "Koi bhi dikkat nahi aayi",
    "Delivery ka time bilkul sahi tha",
    "Mujhe packaging bahut pasand aayi",
    "Product ka color bhi accha tha",
    "Service quality best thi",
    "Main bahut satisfied hoon is product se",
    "Product ki quality best hai",
    "Main is brand par bharosa karta hoon",
    "Delivery time se khush hoon",
    "Customer service perfect thi",
    "Product ki warranty bhi achi hai",
    "Main ise apne family ko recommend karunga",
    "Product ki functionality bahut acchi hai",
    "Service team ne bahut madad ki",
    "Main ise dobara kharidna chahta hoon",
    "Product ke saath sab kuch thik tha",
    "Mujhe yeh product bilkul pasand aaya",
    "Main ise sabko suggest karunga",
    "Quality aur price dono sahi hain",
    "Mujhe product kaafi acha laga",
    "Delivery fast thi",
    "Customer support bahut responsive tha",
    "Main is product se khush hoon",
    "Packaging bilkul safe thi",
    "Product ka design mujhe pasand aaya",
    "Mujhe service achi lagi",
    "Product bilkul as described hai",
    "Main ise recommend karna chahta hoon",
    "Delivery experience bahut accha tha",
    "Product ki performance bahut achi hai",
    "Customer service ne meri madad ki",
    "Main is product ko dobara kharidunga",
    "Quality kaafi achi hai",
    "Mujhe product kaafi useful laga",
    "Packaging mujhe bahut pasand aayi",
    "Main ise sabko recommend karunga",
    "Product ki value mere paise ke liye achi hai",
    "Delivery time perfect tha",
    "Customer support se main khush hoon",
    "Product ki warranty mujhe pasand aayi",
    "Main ise future mein bhi kharidna chahta hoon",
    "Product ki quality bahut acchi hai",
    "Main is brand par bharosa karta hoon",
    "Delivery bilkul time par hui",
    "Customer service ne mujhe support kiya",
    "Product ki functionality mujhe achi lagi",
    "Main ise dobara purchase karunga",
    "Packaging safe thi",
    "Product mujhe bilkul pasand aaya",
    "Mujhe service achi lagi",
    "Main ise sabko recommend karta hoon",
    "Product ki quality bahut achi hai",
    "Delivery fast thi",
    "Customer support bahut accha tha",
    "Main is product se bahut khush hoon",
    "Packaging mujhe pasand aayi",
    "Product design mujhe acha laga",
    "Service quality mujhe bahut pasand aayi",
    "Product bilkul asli hai",
    "Main ise apne dost ko recommend karunga",
    "Delivery timely hui",
    "Customer service ne mujhe madad ki",
    "Product ki value achi hai",
    "Main ise dobara kharidna chahta hoon",
    "Packaging perfect thi",
    "Product ki performance mujhe achi lagi",
    "Main is product ko recommend karta hoon",
    "Delivery kaafi fast thi",
    "Customer support mujhe bahut achha laga",
    "Product mujhe bahut pasand aaya",
    "Main ise future mein bhi kharidna chahta hoon",
    "Packaging safe thi",
    "Product ki quality kaafi achi hai",
    "Main ise sabko recommend karta hoon",
    "Delivery bilkul time par aayi",
    "Customer service bahut responsive thi",
    "Product ki functionality mujhe pasand aayi",
    "Main ise dobara kharidunga",
    "Packaging mujhe bahut pasand aayi",
    "Product design mujhe accha laga",
    "Service quality bahut achi thi",
    "Product bilkul asli lagta hai",
    "Main ise apne doston ko recommend karunga",
    "Delivery fast thi",
    "Customer support mujhe bahut madadgar laga",
    "Product ki value mere liye bahut achi thi",
    "Main ise future mein bhi kharidna chahta hoon",
    "Packaging safe thi",
    "Product quality mujhe bahut pasand aayi",
    "Main ise sabko recommend karta hoon",
    "Delivery timely hui",
    "Customer service bahut achi thi",
    "Product ki performance bahut achi thi",
    "Main is product ko dobara kharidunga",
    "Packaging perfect thi",
    "Product ki functionality mujhe achi lagi",
    "Main ise sabko suggest karta hoon",
    "Delivery fast thi",
    "Customer support mujhe bahut achha laga",
    "Product mujhe bilkul pasand aaya",
    "Main ise apne dost ko recommend karunga",
    "Packaging safe thi",
    "Product ki quality mujhe bahut pasand aayi",
    "Main ise dobara kharidna chahta hoon",
    "Delivery timely hui",
    "Customer service ne meri madad ki",
    "Product ki value bahut achi hai",
    "Main ise sabko recommend karta hoon",
    "Packaging perfect thi",
    "Product ki performance bahut achi hai",
    "Main ise dobara purchase karunga",
    "Delivery fast thi",
    "Customer support bahut responsive tha",
    "Product mujhe bahut accha laga",
    "Main ise sabko recommend karunga",
    "Packaging safe thi",
    "Product ki quality bahut achi hai",
    "Main is brand par bharosa karta hoon",
    "Delivery bilkul time par aayi",
    "Customer service bahut achi thi",
    "Product ki functionality mujhe achi lagi",
    "Main ise dobara kharidunga",
    "Packaging perfect thi",
    "Product ki design mujhe pasand aayi",
    "Main ise sabko suggest karta hoon",
    "Delivery fast thi",
    "Customer support bahut madadgar tha",
    "Product mujhe bahut pasand aaya",
    "Main ise future mein bhi kharidna chahta hoon",
    "Packaging safe thi",
    "Product ki quality bahut acchi hai",
    "Main ise sabko recommend karunga",
    "Delivery timely hui",
    "Customer service ne meri madad ki",
    "Product ki value bahut achi hai",
    "Main ise dobara purchase karunga",
    "Packaging perfect thi",
    "Product ki performance mujhe pasand aayi",
    "Main ise sabko recommend karta hoon",
    "Delivery fast thi",
    "Customer support bahut achi thi",

    # Minglish (around 170)
    "Mala ha product khup avadla",
    "Service is very good",
    "Yeh product kharach top ahe",
    "Delivery khoop lavkar zali",
    "Mala khup satisfaction milala",
    "Price pan ekdam yogya ahe",
    "Customer service khup helpful ahe",
    "Mala punha hi ha product ghyaycha ahe",
    "Quality barobar ahe",
    "Product chi packing ekdam chhan ahe",
    "Use karayla khup sope ahe",
    "Mi khup happy ahe ya purchase var",
    "Friends la pan recommend kelay mi",
    "Service la 5 stars dila mi",
    "Ha product barobar kaam karto",
    "Vastavik madat milali customer support kade",
    "Ha product sobat mi confident ahe",
    "Delivery time pan perfect hota",
    "Mi yeh brand var bharosa karto",
    "Khup chhan product ahe, thanks!",
    "Product chi quality khup chhan ahe",
    "Mi ha product punha kharidin",
    "Delivery time ekdam yogya hota",
    "Customer support khup madat karto",
    "Product kharach original disto",
    "Mi khup satisfied ahe ya product var",
    "Packaging ekdam safe hoti",
    "Product use karne madhe khup sope ahe",
    "Mi ya product la sobat recommend karto",
    "Service khup chhan ahe",
    "Ha product mhanun mala khup anand zala",
    "Mi ha product punha order karnar ahe",
    "Delivery khoop fast hoti",
    "Customer support barobar hota",
    "Product mi kharach avadla",
    "Ha product sobat mi confident ahe",
    "Packaging safe ahe",
    "Product chi warranty barobar ahe",
    "Mi ha brand var bharosa karto",
    "Delivery timely hoti",
    "Customer service khup helpful ahe",
    "Product khup upyogi ahe",
    "Mi ha product barobar kaam karto",
    "Packaging ekdam chhan hoti",
    "Product mi khup avadla",
    "Mi ya product la punha kharidin",
    "Delivery time barobar hota",
    "Customer support khup responsive hota",
    "Product quality ekdam top ahe",
    "Mi ya brand var bharosa karto",
    "Packaging safe hoti",
    "Product kharach original ahe",
    "Mi ha product punha order karnar ahe",
    "Delivery fast hoti",
    "Customer service khup professional ahe",
    "Product quality khup chhan ahe",
    "Mi ha product barobar recommend karto",
    "Packaging ekdam safe hoti",
    "Product use karne madhe khup sope ahe",
    "Mi ya product la sobat recommend karto",
    "Service kharach chhan ahe",
    "Mi ha product punha order karnar ahe",
    "Delivery time barobar hota",
    "Customer support khup madat karto",
    "Product quality ekdam uttam ahe",
    "Mi ha product sobat confident ahe",
    "Packaging safe hoti",
    "Product mi kharach avadla",
    "Mi ya brand var bharosa karto",
    "Delivery timely hoti",
    "Customer service khup helpful ahe",
    "Product kharach original ahe",
    "Mi ha product barobar recommend karto",
    "Packaging ekdam safe hoti",
    "Product quality khup uttam ahe",
    "Mi ha product punha order karnar ahe",
    "Delivery fast hoti",
    "Customer support khup professional ahe",
    "Product use karne madhe khup sope ahe",
    "Mi ya product la sobat recommend karto",
    "Service khup chhan ahe",
    "Mi ha product punha kharidin",
    "Delivery time barobar hota",
    "Customer service khup madat karto",
    "Product quality ekdam uttam ahe",
    "Mi ya brand var bharosa karto",
    "Packaging safe hoti",
    "Product mi khup avadla",
    "Mi ha product barobar recommend karto",
    "Delivery timely hoti",
    "Customer support khup helpful ahe",
    "Product kharach original ahe",
    "Mi ha product punha order karnar ahe",
    "Packaging safe hoti",
    "Product quality khup chhan ahe",
    "Mi ya product la sobat recommend karto",
    "Delivery fast hoti",
    "Customer service khup professional ahe",
    "Product use karne madhe khup sope ahe",
    "Mi ha product punha kharidin",
    "Service khup chhan ahe",
    "Mi ya brand var bharosa karto",
    "Packaging ekdam safe hoti",
    "Product mi khup avadla",
    "Delivery timely hoti",
    "Customer support khup madat karto",
    "Product kharach original ahe",
    "Mi ha product barobar recommend karto",
    "Packaging safe hoti",
    "Product quality ekdam uttam ahe",
    "Mi ya product la punha kharidin",
    "Delivery fast hoti",
    "Customer service khup helpful ahe",
    "Product use karne madhe khup sope ahe",
    "Mi ha product punha order karnar ahe",
    "Service kharach chhan ahe",
    "Mi ya brand var bharosa karto",
    "Packaging safe hoti",
    "Product quality khup chhan ahe",
    "Mi ha product sobat confident ahe",
    "Delivery timely hoti",
    "Customer support khup madat karto",
    "Product mi khup avadla",
    "Mi ya product la sobat recommend karto",
    "Packaging safe hoti",
    "Product quality barobar ahe",
    "Mi ha product barobar recommend karto",
    "Delivery fast hoti",
    "Customer service khup helpful ahe",
    "Product use karne madhe khup sope ahe",
    "Mi ha product punha order karnar ahe",
    "Service khup chhan ahe",
    "Mi ya brand var bharosa karto",
    "Packaging ekdam safe hoti",
    "Product mi khup avadla",
    "Delivery timely hoti",
    "Customer support khup madat karto",
    "Product kharach original ahe",
    "Mi ha product barobar recommend karto",
    "Packaging safe hoti",
    "Product quality khup uttam ahe",
    "Mi ha product punha kharidin",
    "Delivery fast hoti",
    "Customer service khup professional ahe",
    "Product use karne madhe khup sope ahe",
    "Mi ya product la sobat recommend karto",
    "Service khup chhan ahe",
    "Mi ha product punha order karnar ahe",
]